import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    justifyContent: "flex-end",
    alignItems: "center",
  },
  map: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
  },
  loadingContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
  },
  loadingText: {
    marginTop: 10,
    fontSize: 16,
    color: "#276b80",
  },
  errorContainer: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#f5f5f5",
    padding: 20,
  },
  errorText: {
    marginBottom: 20,
    fontSize: 16,
    color: "red",
    textAlign: "center",
  },
  retryButton: {
    backgroundColor: "#276b80",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 5,
  },
  retryButtonText: {
    color: "white",
    fontSize: 16,
  },
  buttonContainer: {
    width: "50%",
    backgroundColor: "rgba(255, 255, 255, 0.8)",
    borderRadius: 10,
    padding: 8,
    marginBottom: 20,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.25,
    shadowRadius: 3.84,
    elevation: 5,
  },
  trackingButton: {
    paddingVertical: 12,
    borderRadius: 8,
    alignItems: "center",
  },
  trackingButtonActive: {
    backgroundColor: "#FF6347",
  },
  trackingButtonInactive: {
    backgroundColor: "#276b80",
  },
  trackingButtonText: {
    color: "white",
    fontSize: 16,
    fontWeight: "bold",
  },
  statusBar: {
    position: "absolute",
    top: 10,
    alignSelf: "center",
    backgroundColor: "rgba(0, 0, 0, 0.7)",
    borderRadius: 20,
    padding: 8,
    paddingHorizontal: 15,
  },
  statusText: {
    color: "white",
    fontSize: 14,
    fontWeight: "500",
  },
  mapControls: {
    position: "absolute",
    right: 10,
    bottom: 100,
    flexDirection: "column",
  },
  mapControlButton: {
    backgroundColor: "rgba(255, 255, 255, 0.9)",
    width: 45,
    height: 45,
    borderRadius: 23,
    justifyContent: "center",
    alignItems: "center",
    marginBottom: 10,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 5,
  },
  mapControlIcon: {
    fontSize: 22,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  userCardContainer: {
    width: "85%",
    justifyContent: "center",
    alignItems: "center",
  },
  userCard: {
    width: "100%",
    borderRadius: 10,
    padding: 5,
  },
  cardText: {
    fontSize: 14,
    marginBottom: 8,
    color: "#555",
  },
  divider: {
    marginVertical: 10,
  },
  cardButton: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    paddingVertical: 8,
  },
  cardButtonText: {
    color: "#276b80",
    fontWeight: "bold",
  },
  modalContent: {
    backgroundColor: "white",
    padding: 20,
    borderRadius: 10,
    width: "80%",
    alignItems: "center",
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    marginBottom: 10,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    padding: 10,
    marginBottom: 10,
    borderRadius: 5,
    width: "100%",
  },
  saveButton: {
    backgroundColor: "#276b80",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    width: "100%",
  },
  saveButtonText: {
    color: "white",
  },
  cancelButton: {
    backgroundColor: "#FF6347",
    padding: 10,
    borderRadius: 5,
    alignItems: "center",
    marginTop: 10,
    width: "100%",
  },
  cancelButtonText: {
    color: "white",
  },
});